[package]
name = "hex-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.16.3"
gtk = { version = "0.5.1", package = "gtk4", features = ["v4_6"] }
sysinfo = "0.26.7"
